### ISSUE TITLE
JCenter will be shut down soon, migrate to Maven Cenral

### ISSUE THREAD

**Issue by szpak** [kuberig-io/kuberig-dsl#20]
I've seen Kuberig at FOSDEM during last weekend and I like a developer-friendly approach for managing Kubernetes configuration!

Unfortunately, Kuberig projects seem to use JCenter to kept the binary artifacts. However, JCenter is [shuting down](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/) rather soon (1st May 2021), so it would be good to migrate releasing to Maven Central (and possibly synchronize old releases with it). kuberig should also switch a place where its own dependencies are downloaded from.

For sample project configuration see:
https://github.com/rwinch/gradle-publish-ossrh-sample

And for sync of the old versions:
https://www.jfrog.com/confluence/display/BT/Syncing+with+Third-Party+Platforms

**Comment by teyckmans** [comment]
Thanks for the report and the references.

I have also read about jcenter shutting down and created an issue on the main kuberig repo: kuberig-io/kuberig#39.

Good idea to synchronize the existing versions also. I'll have a look.

I'll close this one as this is a duplicate. For updates please see the issue on the main repo.
